### must be same as
name: DIME_PDN
suffix: ~  # add suffix to saved images
model: video_dlan
distortion: LLE
scale: 1
crop_border: ~  # crop border when evaluation. If None(~), crop the scale pixels
gpu_ids: [2]

datasets:
  test:
    name: DIME
    mode: VEC_test
    dataroot_GT: ~/Data/DIME/np/test/GT
    dataroot_LQ: ~/Data/DIME/np/test/LQ
    train_size: [256, 256] # [256, 480] #  [480, 256] # [960, 512]  [256, 256]
    cache_data: true
    N_frames: 5
    padding: new_info
    batch_size: 1
    read_all: false  # false true

#### network structures
network_G:
  which_model_G: BaselinePDN
  lldm_config: configs/lldm/lldm.yaml
  vae_config: configs/vqvae/vqgan.yaml
  unet_config: configs/unet/unet.yaml
  lldm_ckpt: ./pretrained/lldm/e200.pt
  frozen_lldm: False
  down_blocks: 2
  nframes: 5
  width: 16
  middle_blk_num: 1
  enc_blk_nums: [1, 1, 1, 28]
  dec_blk_nums: [1, 1, 1, 1]
  dw_expand: 1
  ffn_expand: 2

#### path
path:
  root: ./outputs/DIME_PDN
  pretrain_model_G: ~



